# Generated by Django 5.1.6 on 2025-02-09 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pessoa'),
        ('crm', '0004_cliente_alter_pedido_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
